CREATE TABLE BB_CURRENCY_BID
(
    ID SERIAL PRIMARY KEY NOT NULL,
    CHAT_ID int NOT NULL,
    OWNER_ID varchar(255) NOT NULL,
    OWNER_FIRST_NAME varchar(255),
    OWNER_LAST_NAME varchar(255),
    OWNER_USERNAME varchar(255),
    VALUE int NOT NULL,
    CREATED_AT TIMESTAMP
);
CREATE UNIQUE INDEX BB_CURRENCY_BID_ID_uindex ON BB_CURRENCY_BID (ID);
CREATE INDEX BB_CURRENCY_BID_CREATED_AT_index ON BB_CURRENCY_BID (CHAT_ID, CREATED_AT);