CREATE TABLE BB_DAILY_RATE
(
    ID SERIAL PRIMARY KEY NOT NULL,
    CURRENCY VARCHAR(10) NOT NULL,
    RATE DOUBLE PRECISION NOT NULL,
    DATE DATE NOT NULL
);
CREATE UNIQUE INDEX BB_DAILY_RATE_ID_uindex ON BB_DAILY_RATE (ID);
CREATE INDEX BB_DAILY_RATE_DATE_CURR_index ON BB_DAILY_RATE (DATE, CURRENCY);