CREATE TABLE BB_USER_ROLES
(
    ID SERIAL PRIMARY KEY NOT NULL,
    USER_ID INT NOT NULL,
    ROLE VARCHAR(10) NOT NULL
);
CREATE UNIQUE INDEX BB_USER_ROLES_uindex ON BB_USER_ROLES (ID);
CREATE INDEX BB_USER_ROLES_userid_idx ON BB_USER_ROLES (USER_ID);