CREATE TABLE BB_STATISTICS
(
    ID SERIAL PRIMARY KEY NOT NULL,
    POSTED_DATE DATE NOT NULL,
    MESSAGE_COUNT INT,
    CHAT_ID BIGINT NOT NULL,
    AUTHOR_ID BIGINT NOT NULL,
    AUTHOR_NAME varchar(100) NOT NULL
);