version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "telegram-bot-bumblebee-core/build.gradle" }}-{{ checksum "telegram-bot-api/build.gradle" }}-{{ checksum "gradle.properties" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "telegram-bot-bumblebee-core/build.gradle" }}-{{ checksum "telegram-bot-api/build.gradle" }}-{{ checksum "gradle.properties" }}
        
      # run tests!
      - run: gradle test

